TU-NHM-elurikkus/commons

grails-app/views/_manifest.gsp
grails-app/views/_menu.gsp
web-app/css/elurikkus-common.css

* Add a template for linking site manifest and favicons;
* update menu style.

Add manifest reference; update styles

---

grails-app/views/_menu.gsp
web-app/css/elurikkus-common.css
web-app/css/menu.css

* Add style for sub-page titles and subtitles;
* update burger menu's three bar icon.

Update burger icon & common style

---

grails-app/conf/ElurikkusCommonsResources.groovy
grails-app/views/_menu.gsp
web-app/css/elurikkus-common.css

* Update burger menu style;
* include Fontawesome with ALA/cmmons menu package.

Update burger menu style

---

grails-app/i18n/messages.properties
grails-app/i18n/messages_et.properties
grails-app/views/_menu.gsp

Translate the menu

---

grails-app/conf/spring/resources.groovy
grails-app/i18n/messages.properties
grails-app/i18n/messages_et.properties
grails-app/taglib/elurikkus/commons/LocaleSwitcherTagLib.groovy
grails-app/views/_menu.gsp
test/unit/elurikkus/commons/LocaleSwitcherTagLibSpec.groovy

Add locale switching logic

---

grails-app/assets/stylesheets/elurikkus-common.css
grails-app/views/_menu.gsp

* Restyle burger links
* Remove "atlases"

[#149842983] Sync menu to cms

---

grails-app/assets/stylesheets/elurikkus-common.css

I didn't write styles for lefty floatation yet. Will do when it's needed.
[#150742164]

Inline group style

---

grails-app/assets/stylesheets/elurikkus-common.css

Add low-key style to augment Bootstrap 4's cards

---

grails-app/assets/stylesheets/elurikkus-common.css

Right-align text in right-aligned control groups

---

grails-app/assets/stylesheets/elurikkus-common.css

Add more space between secondary menu links

---

grails-app/assets/stylesheets/elurikkus-common.css
grails-app/views/_menu.gsp

* Move "Occurrence Records" to the last item of top-menu [#152794051]
* Fix menu cursor hover in FF [#152724405]

Menu tweaks

---

grails-app/assets/javascripts/common.js
grails-app/assets/javascripts/polyfills.js

Fix for Rollbar items 305 and 307.
[#152883139]

Add a couple of polyfills

---

grails-app/assets/stylesheets/elurikkus-common.css

Set button border radius default value

---

grails-app/i18n/messages.properties
grails-app/i18n/messages_et.properties

Add behaviour & life stage translations

---

grails-app/assets/stylesheets/elurikkus-common.css

Add opacity transition effect to menu items

---

grails-app/assets/stylesheets/elurikkus-common.css

Tweak explore data menu addon position

---

grails-app/i18n/messages.properties
grails-app/i18n/messages_et.properties
grails-app/views/_footer.gsp

Assummin https://github.com/TU-NHM/elurikkus-cms/pull/99 is merge and deployed, of course

Added NATARC logo to footer

---

grails-app/i18n/messages.properties
grails-app/i18n/messages_et.properties

* establishment_means messages
* occurrence_type messages
* modified identification_qualifier messages

added new translations

---

grails-app/assets/stylesheets/elurikkus-common.css
grails-app/i18n/messages.properties
grails-app/views/_footer.gsp

Add DiSSCo logo to footer

---

grails-app/assets/stylesheets/elurikkus-common.css
grails-app/i18n/messages.properties
grails-app/i18n/messages_et.properties
grails-app/views/_footer.gsp

Add new logos to eElurikkus (ALA) footer
